server:
  port: 18080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-password: p8labs

spring:
  application:
    name: member-service

  datasource:
    url: jdbc:mysql://localhost:3306/cafe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
